server:
  port: 8901

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skill?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
# spring redis 的相关配置
  redis:
    host: 192.168.2.87
    port: 6379
    password: zheng
    database: 0
    timeout: 5000

# 自定义属性
skill:
  # 自定义属性，代表的秒杀的限购3件
  maxcount: 3
  # 自定义的，aes加密算法的key
  aesKey: Pnoic2vFfLljKNRU7FHoFw==

# mybatis的扫描xml的包的路径
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
